import { Complaint } from "./types";

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: "mock-001",
    folio: "VE-2026-1001",
    role: "alumno",
    content: "Un compañero de mi salón me ha estado molestando durante semanas. Me dice cosas feas, me quita mis cosas y cuando le digo a los maestros no hacen nada. Ya no quiero ir a la escuela.",
    category: "acoso_escolar",
    urgency: "critical",
    status: "en_proceso",
    isAnonymous: false,
    contentHash: "abc123",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), message: "La dirección tomó conocimiento del caso." },
      { status: "en_proceso", timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), message: "Se citó a los padres de ambas partes." },
    ],
    sentimentScore: 82,
  },
  {
    id: "mock-002",
    folio: "VE-2026-1002",
    role: "padre",
    content: "El maestro de matemáticas de 4to grado llega tarde constantemente, a veces hasta 20 minutos después del timbre. Los niños se quedan solos en el salón sin supervisión.",
    category: "docente",
    urgency: "high",
    status: "en_revision",
    isAnonymous: true,
    contentHash: "def456",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), message: "Se solicitó informe al subdirector académico." },
    ],
    sentimentScore: 65,
  },
  {
    id: "mock-003",
    folio: "VE-2026-1003",
    role: "alumno",
    content: "El baño de hombres de la planta baja lleva tres semanas sin tener agua. Tenemos que subir al segundo piso y a veces llegamos tarde a clase.",
    category: "infraestructura",
    urgency: "medium",
    status: "resuelta",
    isAnonymous: false,
    contentHash: "ghi789",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_proceso", timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), message: "Se contrató servicio de plomería." },
      { status: "resuelta", timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), message: "El problema de plomería fue reparado satisfactoriamente." },
    ],
    adminResponse: "El servicio de mantenimiento reparó la tubería el día 28 de abril. Gracias por reportarlo.",
    sentimentScore: 40,
  },
  {
    id: "mock-004",
    folio: "VE-2026-1004",
    role: "padre",
    content: "Mi hija me contó que una persona desconocida estuvo rondando la escuela durante el recreo y que nadie de seguridad hizo nada. Estoy muy preocupado por la seguridad.",
    category: "seguridad",
    urgency: "critical",
    status: "en_proceso",
    isAnonymous: false,
    contentHash: "jkl012",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_proceso", timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), message: "Se notificó al personal de seguridad y se revisaron cámaras." },
    ],
    sentimentScore: 88,
  },
  {
    id: "mock-005",
    folio: "VE-2026-1005",
    role: "docente",
    content: "Llevamos dos meses sin recibir los materiales didácticos que se solicitaron. Los alumnos no tienen libros de texto actualizados y la dirección no da respuesta.",
    category: "administrativo",
    urgency: "high",
    status: "en_revision",
    isAnonymous: false,
    contentHash: "mno345",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 58,
  },
  {
    id: "mock-006",
    folio: "VE-2026-1006",
    role: "alumno",
    content: "El patio de recreo tiene una barda rota con alambres de púas expuestos. Ya dos niños se han lastimado. Alguien se va a lastimar gravemente si no lo arreglan.",
    category: "infraestructura",
    urgency: "critical",
    status: "en_proceso",
    isAnonymous: false,
    contentHash: "pqr678",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_proceso", timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), message: "Se acordonó el área y se solicitó reparación urgente." },
    ],
    sentimentScore: 75,
  },
  {
    id: "mock-007",
    folio: "VE-2026-1007",
    role: "padre",
    content: "La maestra de inglés pone calificaciones arbitrarias. Mi hijo estudió mucho y sacó 6, pero otros niños que no estudian sacan 9. Creemos que hay favoritismo.",
    category: "docente",
    urgency: "medium",
    status: "recibida",
    isAnonymous: true,
    contentHash: "stu901",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 52,
  },
  {
    id: "mock-008",
    folio: "VE-2026-1008",
    role: "personal",
    content: "El comedor escolar tiene cucarachas. Ya lo reporté a la directora hace un mes y no han fumigado. Los niños comen ahí todos los días.",
    category: "infraestructura",
    urgency: "high",
    status: "en_revision",
    isAnonymous: false,
    contentHash: "vwx234",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 70,
  },
  {
    id: "mock-009",
    folio: "VE-2026-1009",
    role: "alumno",
    content: "Un grupo de niños de sexto me esperan a la salida y me amenazan. Tengo miedo de salir solo. Ya no duermo bien pensando en lo que puede pasar.",
    category: "acoso_escolar",
    urgency: "critical",
    status: "en_proceso",
    isAnonymous: false,
    contentHash: "yza567",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_proceso", timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), message: "Se contactó al orientador escolar y se notificó a los padres." },
    ],
    sentimentScore: 91,
  },
  {
    id: "mock-010",
    folio: "VE-2026-1010",
    role: "padre",
    content: "La cooperativa escolar cobra precios muy elevados y no da cambio. Además cobran una cuota mensual obligatoria que nunca se mencionó en la inscripción.",
    category: "administrativo",
    urgency: "low",
    status: "recibida",
    isAnonymous: true,
    contentHash: "bcd890",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 35,
  },
  {
    id: "mock-011",
    folio: "VE-2026-1011",
    role: "docente",
    content: "El proyector del salón 3B lleva 4 meses descompuesto. He reportado el problema varias veces y nunca se atiende. Afecta mis clases directamente.",
    category: "infraestructura",
    urgency: "medium",
    status: "en_revision",
    isAnonymous: false,
    contentHash: "efg123",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 45,
  },
  {
    id: "mock-012",
    folio: "VE-2026-1012",
    role: "alumno",
    content: "El maestro de educación física nos pone a hacer ejercicio muy fuerte bajo el sol sin darnos descanso ni agua. Un compañero se desmayó la semana pasada.",
    category: "seguridad",
    urgency: "high",
    status: "en_proceso",
    isAnonymous: false,
    contentHash: "hij456",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_proceso", timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), message: "Se habló con el maestro sobre protocolos de actividad física." },
    ],
    sentimentScore: 73,
  },
  {
    id: "mock-013",
    folio: "VE-2026-1013",
    role: "padre",
    content: "La dirección organizó un evento escolar y cobró una cuota sin autorización previa de la sociedad de padres. No se rindieron cuentas del dinero recaudado.",
    category: "administrativo",
    urgency: "medium",
    status: "recibida",
    isAnonymous: true,
    contentHash: "klm789",
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 48,
  },
  {
    id: "mock-014",
    folio: "VE-2026-1014",
    role: "alumno",
    content: "Hay una fuga de agua en el techo del salón 5A. Cuando llueve el suelo se moja y resbalamos. Además huele a humedad todo el tiempo.",
    category: "infraestructura",
    urgency: "high",
    status: "en_revision",
    isAnonymous: false,
    contentHash: "nop012",
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 60,
  },
  {
    id: "mock-015",
    folio: "VE-2026-1015",
    role: "personal",
    content: "El director humilla a los empleados frente a los alumnos cuando cometemos un error. El ambiente laboral es muy hostil y varios compañeros están pensando en renunciar.",
    category: "administrativo",
    urgency: "high",
    status: "en_revision",
    isAnonymous: true,
    contentHash: "qrs345",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { status: "recibida", timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() },
      { status: "en_revision", timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    sentimentScore: 77,
  },
];
